services:
  mailpit:
    image: axllent/mailpit
    container_name: ${MAIL_HOST}
    restart: unless-stopped
    ports:
      - '${MAILPIT_UI_PORT}:8025' # Web UI
      - ${MAILPIT_SMTP_PORT}:1025 # SMTP
    networks:
      - net
networks:
    net:

