services:
    mailpit:
        image: axllent/mailpit
        container_name: ${MAIL_HOST}
        restart: unless-stopped
        ports:
            - '${MAIL_PORT}:1025' # SMTP server
            - '8025:8025' # Web UI
        networks:
            - net
networks:
    net:
