services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: laravel-dev
    ports:
      - '${APP_PORT}:8000'
      - '5173:5173'
    networks:
      - net

networks:
    net:

